apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-jp-api
  namespace: jpapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-jp-api
  template:
    metadata:
      labels:
        app: new-jp-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: grade-submission-api
          image: ghcr.io/codeicu120/new-jp:56356b7ca9baa0a8a3d9082f40955bd6043c917e
          ports:
            - containerPort: 8002
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          volumeMounts:
            - name: app-config
              mountPath: /app/config/config.yaml
              subPath: config.yaml
      volumes:
        - name: app-config
          configMap:
            name: new-jp-config
---
apiVersion: v1
kind: Service
metadata:
  name: new-jp-api
  namespace: jpapi
spec:
  selector:
    app: new-jp-api
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP
