apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: new-jp-api-ingress
  namespace: jpapi
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: knewjp.ipixiv.com   # 换成你的域名
      http:
        paths:
          - path: /api/v2
            pathType: Prefix
            backend:
              service:
                name: new-jp-api
                port:
                  number: 8002
